### ISSUE TITLE
No file blob_line_skel_1mm_2nii.nii.gz

### ISSUE THREAD

**Issue by r03ert0** [illdopejake/Hippocampus_AP_Axis#1]
Hello!
Thank you for making the code available :D
I'm trying to run it all, but this file is not inside `Data/`. I have to recompute it with the script `hipp_medial_axis_transform.sh`?

**Comment by illdopejake** [comment]
Hi Roberto! 

So, the hipp_medial_axis_transform.sh will create that file. However, that's the one part of the codebase that requires minc-toolkit, which I realize not everyone has. I wanted to minimize the number of image files where possible, but I think its reasonable to include this one in Data/. I'll add it.

Thanks for going through the code. Helpful to have another set of eyes ;-)

**Comment by illdopejake** [comment]
Okay, it's in there. Don't hesitate to reach out if you run into other issues.

**Comment by r03ert0** [comment]
thank you! \o/
